
title: cmsdato
timezone: UTC
collections:
  brands:
    title: Brands
    output: false
  events:
    title: Events
    output: false
  posts:
    title: Posts
    output: true
  projets:
    title: Projets
    output: false
  teams:
    title: Teams
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    hero: ''
    customclass: ''
    tags: []
    description_hero: ''
    extrait: ''
    auteur: ''
    comments: 'true'
- scope:
    path: ''
    type: teams
  values:
    layout: auteur
    avatar: ''
    twitter_username: ''
    description: ''
- scope:
    path: ''
    type: projets
  values:
    visuel: ''
    background: ''
    link: ''
    description: ''
- scope:
    path: ''
    type: brands
  values:
    logo: ''
    link: ''
- scope:
    path: ''
    type: events
  values:
    end_date: ''
    type: ''
    visuel: ''
    background: ''
    full_frame: ''
    description: ''
    bouton: ''
    link: ''
email:
description: cmsdatotest
baseurl: ''
url: https://arthur-koenig.github.io/cmsdato.github.io
twitter_username:
github_username:
github.url:
gems:
- jekyll-paginate
paginate: 6
paginate_path: "blog/page:num/"
markdown: kramdown
permalink: "blog/:title"
